core/accounts/urls.py
from django.urls import path, include
from . import views

app_name = "accounts"

urlpatterns = [
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("register/", views.RegisterView.as_view(), name="register"),
    # path("api/v1/", include("accounts.api.v1.urls")),
    # path("", include("django.contrib.auth.urls")),

]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions

schema_view = get_schema_view(
    openapi.Info(
        title="Blog API",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls")),
    path("accounts/", include("accounts.urls")),
    path('api-auth/', include('rest_framework.urls')),
    path(
        "swagger.<format>/",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path(
        "redoc/",
        schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),

]

core/todo/api/v1/urls.py
from django.urls import path
from todo.api.v1 import views
from rest_framework.routers import DefaultRouter, SimpleRouter

app_name = "tasks_api"

# urlpatterns = [
#     path("", views.TaskListgenericView.as_view(), name="list"),
# ]
router = SimpleRouter()
router.register("task", views.TaskListgenericView, basename="task")
urlpatterns = router.urls

core/todo/urls.py
from django.urls import path, include
from . import views

app_name = "todo"

urlpatterns = [
    path("", views.TaskList.as_view(), name="task_list"),
    path("create/", views.TaskCreate.as_view(), name="create_task"),
    path("update/<int:pk>/", views.TaskUpdate.as_view(), name="update_task"),
    path("complete/<int:pk>/", views.TaskComplete.as_view(), name="complete_task"),
    path("undo/<int:pk>/", views.TaskUndo.as_view(), name="undo_task"),
    path("delete/<int:pk>/", views.TaskDeleteView.as_view(), name="delete_task"),
    path("api/v1/", include("todo.api.v1.urls")),
]

core/todo/models.py
from django.contrib.auth import get_user_model
from django.db import models

# Create your models here.
User = get_user_model()

class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=200)
    complete = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        order_with_respect_to = "user"

core/todo/forms.py
from django import forms
from .models import Task

# Reordering Form and View


class TaskUpdateForm(forms.ModelForm):
    title = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control rounded-4",
                "name": "title",
                "placeholder": "enter the title",
            }
        ),
        label="",
    )

    class Meta:
        model = Task
        fields = ("title",)

core/todo/api/v1/views.py
from datetime import timezone

from rest_framework.views import APIView
from rest_framework.generics import GenericAPIView
from rest_framework.response import Response
from rest_framework import status, permissions, viewsets
from rest_framework import viewsets
from rest_framework.exceptions import PermissionDenied

from todo.api.v1.serializers import TaskSerializer
from todo.models import Task
from permissions import IsOwner


class TaskListgenericView(viewsets.ModelViewSet):
    serializer_class = TaskSerializer
    permission_classes = (IsOwner,)

    # queryset = Task.objects.all()
    def get_queryset(self):
        return Task.objects.filter(user=self.request.user).order_by('-updated_date')

    def get_object(self):
        obj = super().get_object()
        self.check_object_permissions(self.request, obj)  # raises if not allowed
        return obj

    def perform_create(self, serializer):
        serializer = self.get_serializer(data=serializer.data)
        serializer.is_valid(raise_exception=True)
        serializer.save(user=self.request.user)
        return Response(serializer.data, status=status.HTTP_201_CREATED)

core/todo/views.py
from django.shortcuts import redirect, render
from django.views.generic.list import ListView
from django.views.generic.edit import (
    CreateView,
    UpdateView,
    DeleteView,
)
from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import TaskUpdateForm
from django.views import View
from .models import Task


# Create your views here.
class TaskList(LoginRequiredMixin, ListView):
    template_name = "todo/list_task.html"
    context_object_name = "tasks"
    model = Task

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


class TaskCreate(LoginRequiredMixin, CreateView):
    model = Task
    fields = ["title"]
    success_url = reverse_lazy("todo:task_list")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class TaskUpdate(LoginRequiredMixin, UpdateView):
    model = Task
    success_url = reverse_lazy("todo:task_list")
    form_class = TaskUpdateForm
    template_name = "todo/update_task.html"

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.user != self.request.user:
            raise PermissionDenied("This task is not yours")
        return obj


class TaskComplete(LoginRequiredMixin, View):
    model = Task
    success_url = reverse_lazy("todo:task_list")

    def get(self, request, *args, **kwargs):
        object = Task.objects.get(id=kwargs.get("pk"))
        if object.user == request.user:
            object.complete = True
            object.save()
            return redirect(self.success_url)
        raise PermissionDenied("This task is not yours")


class TaskUndo(LoginRequiredMixin, View):
    model = Task
    success_url = reverse_lazy("todo:task_list")

    def get(self, request, *args, **kwargs):
        object = Task.objects.get(id=kwargs.get("pk"))
        if object.user == request.user:
            object.complete = False
            object.save()
            return redirect(self.success_url)
        raise PermissionDenied("This task is not yours")


class TaskDeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    context_object_name = "task"
    success_url = reverse_lazy("todo:task_list")
    template_name = "todo/task_confirm_delete.html"

    def get_queryset(self):
        return Task.objects.filter(user=self.request.user)

    def post(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.user != request.user:
            raise PermissionDenied("This task is not yours")
        obj.delete()
        return redirect(self.success_url)

core/todo/templates/todo/list_task.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Todo List {% endblock %}
{% block extra_css %}{% endblock %}

{% block content %}
<div class="modal modal-signin position-static d-block  py-5" tabindex="-1" role="dialog" id="modalSignin">
  <div class="modal-dialog" role="document">
    <div class="modal-content rounded-5 shadow">
      <div class="modal-header p-5 pb-4 border-bottom-0">
        <!-- <h5 class="modal-title">Modal title</h5> -->
        <h2 class="fw-bold mb-0">Todo App</h2>
        <a type="button" class="btn-close" href="{% url 'accounts:logout' %}"></a>
      </div>

      <div class="modal-body p-5 pt-0">

        <form class="pt-3" method="POST" action="{% url 'todo:create_task' %}">
          {% csrf_token %}
          <div class="input-group mb-3">
            <input type="text" class="form-control rounded-4" name="title" placeholder="Enter task title"
              aria-label="Recipient's username" aria-describedby="button-addon2">
            <button class="btn btn-primary" type="submit">Add</button>
          </div>


          <hr class="my-4">
          {% for task in tasks %}
          <div class="input-group py-1">
            <span type="text" class="form-control" aria-label="Text input with segmented dropdown button">
              {% if task.complete == True %}
              <strike>{{task.title}}</strike>
              {% else %}
              <span>{{task}}</span>
              {% endif %}
            </span>
            <a type="button" class="btn btn-danger" href="{% url 'todo:delete_task' task.id %}"><i class="bi bi-trash"></i></a>
            <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown"
              aria-expanded="false">
              <span class="visually-hidden">Toggle Dropdown</span>
            </button>
            <ul class="dropdown-menu dropdown-menu-end">
                {% if task.complete == False %}
              <li><a class="dropdown-item" href="{% url 'todo:complete_task' task.id %}">Done</a></li>
                {% else %}
                <li><a class="dropdown-item" href="{% url 'todo:undo_task' task.id %}">Undo</a></li>
                {% endif %}
              <li><a class="dropdown-item" href="{% url 'todo:update_task' task.id %}">Edit</a></li>
            </ul>
          </div>
      
          {% endfor %}          
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block extra_js %}{% endblock %}

core/todo/templates/todo/task_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Todo Delete {% endblock %}
{% block extra_css %}{% endblock %}
{% block content %}
<form method="post" class="text-center p-4 border rounded shadow-sm bg-light">
    {% csrf_token %}
    <h5 class="mb-3">Are you sure you want to delete <strong>"{{ task }}"</strong>?</h5>

    <div class="d-flex justify-content-center gap-2">
        <button type="submit" class="btn btn-danger px-4">Yes, Delete</button>
        <a href="{% url 'todo:task_list' %}" class="btn btn-secondary px-4">Cancel</a>
    </div>
</form>
{% endblock %}

core/todo/templates/todo/update_task.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Edit Task {% endblock %}
{% block extra_css %}
{% endblock %}

{% block content %}
<div class="modal modal-signin position-static d-block  py-5" tabindex="-1" role="dialog" id="modalSignin">
	<div class="modal-dialog" role="document">
		<div class="modal-content rounded-5 shadow">
			<div class="modal-header p-5 pb-4 border-bottom-0">
				<!-- <h5 class="modal-title">Modal title</h5> -->
				<h2 class="fw-bold mb-0">Edit Form</h2>
				<a type="button" class="btn-close" href="{% url 'todo:task_list' %}"></a>
			</div>

			<div class="modal-body p-5 pt-0">

				<form method="POST" action="">
					{% csrf_token %}
					<div class="form-floating mb-3">						
                        {{form}}
						<!-- <label for="floatingInput">Title</label> -->
					</div>
					<button class="w-100 mb-2 btn btn-lg rounded-4 btn-primary" type="submit">Change</button>
				</form>				
			</div>
		</div>
	</div>
</div>
{% endblock %}

{% block extra_js %}{% endblock %}

<div class="header-bar">
    <a href="{% url 'todo:tasks' %}">&#8592; Back</a>
</div>


<div class="card-body">
    <form method="POST" action="">
        {% csrf_token %}
        {{form.as_p}}
        <input class="button" type="submit" value="Submit">
    </form>
</div>